### ISSUE TITLE
请教yuv格式和mjpeg格式的效率对比

### ISSUE THREAD

**Issue by zongren** [tsinglink/uvccamera#1]
你好，我看项目介绍写的
```
使用libyuv进行格式转换,提高了效率.
```

请问能具体说说怎么提高了效率吗，多谢！

**Comment by jiaozebo** [comment]
原作者使用c代码进行yuv转换.效率不高,尤其分辨率更高的情况下更是如此. 你可以参考
libuvccamera/src/main/jni/libuvc/src/frame-mjpeg.c
这个文件的变动历史.
libyuv是Google出的效率非常高的yuv库.底层使用了平台相关的汇编代码进行加速. 你可以搜索libyuv了解下
我主要是把yuv转换的逻辑,使用libyuv处理了.

**Comment by jiaozebo** [comment]
关于mjpeg和yuv, 我所知不多:
uvc协议里面支持mjpeg传输,但不支持yuv传输,毕竟yuv数据量惊人,也传不过来.
作者做的是用jpeg库将mjpeg解码成YUV422,然后转成yuv420,我也就是在YUV422转yuv420的过程中进行了优化.

**Comment by zongren** [comment]
好的，多谢
