### ISSUE TITLE
How to capture images? 

### ISSUE THREAD

**Issue by kkmehta03** [tsinglink/uvccamera#7]
Hi there! 
First off, thanks for this amazing repository! 
I wanted to  know how we can capture images using this library. 
Assume there's a button to capture, can you roughly give the pseudo code or link where we can capture photos with it? 

Thanks!

**Comment by jiaozebo** [comment]
you can use YuvImage to save a yuv format picture to jpeg.

**Comment by kkmehta03** [comment]
Thank you! Is there an API or documentation reference I can follow on how to capture image using YuvImage? 
I tried by import YuvImage class from `import android.graphics.YuvImage` but how should the image stream actually get captured? Also, i noticed there's another YuvImage class in `libjpeg turbo` package under `libuvccamera` library. Is that the class to be imported?
I'm a novice developer hence these basic questions :smile: 
If you have any reference code I can follow, or any documentation to get me started, I'd really appreciate it. 
Thank you!

**Comment by jiaozebo** [comment]
> Thank you! Is there an API or documentation reference I can follow on how to capture image using YuvImage? I tried by import YuvImage class from `import android.graphics.YuvImage` but how should the image stream actually get captured? Also, i noticed there's another YuvImage class in `libjpeg turbo` package under `libuvccamera` library. Is that the class to be imported? I'm a novice developer hence these basic questions 😄 If you have any reference code I can follow, or any documentation to get me started, I'd really appreciate it. Thank you!

I've added this function to the demo.  see [68afcd](https://github.com/tsinglink/uvccamera/commit/68afcdfb409bb745c620545d0d39af0039c5e679)

https://user-images.githubusercontent.com/35994794/156747624-5e0e372c-a4ed-467c-b6c4-1d187bb1a81c.mp4

**Comment by kkmehta03** [comment]
Thank you! this is great!
